# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2f4bed23b956884727666b48dc6e7e51023f6f62e94ce7ab29117756fee7fda5b25ffb5fa6c42a380b4fc993c11b68f4e356a0af533aa0c592ca239a028e91a

test:
  secret_key_base: 9f6e1cf5a219328f097c4dcfbb2aa42670c1bd73d057ec7f320914f1a2fe7fc1b64ae0533e907186cde05b93b80e45057ebca40b9e911e752c238dcbcc17f8f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
